# fly.toml file generated for buzzer on 2022-11-13T13:34:59-08:00

app = "buzzer"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "Dockerfile"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 7777
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    # these are artifically high since this toy project
    # only supports a single-server architecture currently.
    hard_limit = 3500
    soft_limit = 3445
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
